version: '3.7'

services:
  backend:
    image: ehuan2/srs-backend:latest
    ports:
      - 8080:8080
    environment: 
      PYTHONUNBUFFERED: 1
    command: ["python", "app.py"]

  db:
    image: "postgres" 
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/data
    ports:
      - 5432:5432
  
volumes:
  db-data: