"""empty message

Revision ID: 2150fea308aa
Revises: 556fcf93c376
Create Date: 2023-06-12 23:45:22.541919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2150fea308aa'
down_revision = '556fcf93c376'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incorrect_answer_bin_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bin_type', sa.Integer(), nullable=True))
        batch_op.alter_column('from_review_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('to_review_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('time_delay_hours',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'bin', ['incorrect_answer_bin_id'], ['id'])
        batch_op.drop_column('incorrect_answer_decrementer')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('review_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vocab', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('review_type_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.create_foreign_key(None, 'review_type', ['review_type_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('review_type_id')
        batch_op.drop_column('vocab')

    with op.batch_alter_table('review_type', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('deck', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('bin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('incorrect_answer_decrementer', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('time_delay_hours',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('to_review_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('from_review_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('bin_type')
        batch_op.drop_column('incorrect_answer_bin_id')

    # ### end Alembic commands ###
