"""empty message

Revision ID: d66adb417f4b
Revises: 
Create Date: 2023-06-15 08:02:41.811212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66adb417f4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('review_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_review_type_id', sa.Integer(), nullable=True),
    sa.Column('to_review_type_id', sa.Integer(), nullable=True),
    sa.Column('time_delay_hours', sa.Integer(), nullable=True),
    sa.Column('wrong_answer_bin_id', sa.Integer(), nullable=True),
    sa.Column('correct_answer_bin_id', sa.Integer(), nullable=True),
    sa.Column('bin_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['correct_answer_bin_id'], ['bin.id'], ),
    sa.ForeignKeyConstraint(['from_review_type_id'], ['review_type.id'], ),
    sa.ForeignKeyConstraint(['to_review_type_id'], ['review_type.id'], ),
    sa.ForeignKeyConstraint(['wrong_answer_bin_id'], ['bin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['bin.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['deck.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('vocab', sa.String(length=256), nullable=False),
    sa.Column('review_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_type_id'], ['review_type.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary')
    op.drop_table('card')
    op.drop_table('bin')
    op.drop_table('review_type')
    op.drop_table('deck')
    # ### end Alembic commands ###
